project:
  type: website
  output-dir: docs

website:
  title: "minstar"
  navbar:
    right:
      - about.qmd
      - profile.qmd
      - icon: github
        href: https://github.com/Noveled/minstar_blog/
format:
  html:
    theme: lux
    css: styles.css


